from pathlib import Path

from slopcount.detectors.env_markers import EnvMarkerDetector
from slopcount.evidence import Category
from slopcount.scanner import read_text, scan


def test_presence_and_headers(tmp_path):
    (tmp_path / "CLAUDE.md").write_text("Be nice.\n")
    (tmp_path / ".claude").mkdir()
    (tmp_path / "gen.py").write_text("# Generated by Claude Code\nx = 1\n")
    det = EnvMarkerDetector()
    evs = det.detect(tmp_path, scan(tmp_path), lambda p: read_text(p))
    files = {e.file for e in evs}
    assert "CLAUDE.md" in files and ".claude" in files and "gen.py" in files
    gen = [e for e in evs if e.file == "gen.py"][0]
    assert gen.weight == 5 and gen.category is Category.AGENCY
