from slopcount.detectors.env_markers import EnvMarkerDetector
from slopcount.evidence import Category
from slopcount.scanner import read_text, scan


def test_presence_and_headers(tmp_path):
    (tmp_path / "CLAUDE.md").write_text("Be nice.\n")
    (tmp_path / ".claude").mkdir()
    (tmp_path / "gen.py").write_text("# Generated by Claude Code\nx = 1\n")
    det = EnvMarkerDetector()
    evs = det.detect(tmp_path, scan(tmp_path), lambda p: read_text(p))
    files = {e.file for e in evs}
    assert "CLAUDE.md" in files and ".claude" in files and "gen.py" in files
    gen = next(e for e in evs if e.file == "gen.py")
    assert gen.weight == 5 and gen.category is Category.AGENCY


def test_marker_semantics(tmp_path):
    det = EnvMarkerDetector()
    (tmp_path / "sub").mkdir()
    (tmp_path / "sub" / "CLAUDE.md").write_text("hi\n")  # nested basename
    (tmp_path / ".github").mkdir()
    (tmp_path / ".github" / "copilot-instructions.md").write_text("x\n")  # full relpath
    # line 6: no hit
    (tmp_path / "six.py").write_text("\n" * 5 + "# Generated by Claude Code\nx = 1\n")
    (tmp_path / "low.py").write_text("# generated by claude code\nx = 1\n")  # lowercase: no hit
    evs = det.detect(tmp_path, scan(tmp_path), lambda p: read_text(p))
    files = {e.file for e in evs}
    assert "sub/CLAUDE.md" in files
    assert ".github/copilot-instructions.md" in files
    assert "six.py" not in files and "low.py" not in files
